- implementation: nodestream_akamai.appsec_coverage:AkamaiAppSecCoverageExtractor
  arguments:
    base_url: !env 'base_url'
    client_token: !env 'client_token'
    client_secret: !env 'client_secret'
    access_token: !env 'access_token'
    account_key: !env 'account_key'
  annotations:
  - live
  - test
- implementation: nodestream.interpreting:Interpreter
  arguments:
    interpretations:
    - type: source_node
      node_type: akamai_waf_policy
      normalization:
        do_remove_trailing_dots: true
      key:
        policyId: !jmespath 'policyId'
    - type: relationship
      node_type: endpoint
      node_key: 
        policyId: !jmespath 'hostname'
      relationship_type: PROTECTED_BY
      outbound: false

- implementation: nodestream.databases:GraphDatabaseWriter
  arguments:
    batch_size: 100
    database: !env NEO4J_DATABASE_NAME
    uri: !env NEO4J_ENDPOINT
    username: !env NEO4J_DATABASE_USERNAME
    password: !env NEO4J_DATABASE_PASSWORD