- implementation: nodestream_akamai.ehn:AkamaiEHNExtractor
  arguments:
    base_url: !env 'base_url'
    client_token: !env 'client_token'
    client_secret: !env 'client_secret'
    access_token: !env 'access_token'
    account_key: !env 'account_key'
  annotations:
  - live
  - test
- implementation: nodestream.interpreting:Interpreter
  arguments:
    interpretations:
    - type: source_node
      node_type: akamai_edgehost
      normalization:
        do_remove_trailing_dots: true
      key:
        edgeHostnameId: !jmespath 'edgeHostnameId'
    - type: properties
      properties:
        edgeHostname: !jmespath 'edgeHostname'
        ipVersionBehavior: !jmespath 'ipVersionBehavior'
    - type: relationship
      node_type: endpoint
      node_key: 
        fqdn: !jmespath 'recordName'
      relationship_type: HAS_RECORD

- implementation: nodestream.databases:GraphDatabaseWriter
  arguments:
    batch_size: 100
    database: !env NEO4J_DATABASE_NAME
    uri: !env NEO4J_ENDPOINT
    username: !env NEO4J_DATABASE_USERNAME
    password: !env NEO4J_DATABASE_PASSWORD